export const HomeObjOne = {
    id: 'sobre',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Banco Premium',
    headline: 'Transações ilimitadas e sem taxas', 
    description: 'Acesso especial de convidado ao nosso aplicativo exclusivo, permitindo transações ilimitadas sem nenhuma taxa adicional',
    buttonLabel: 'Clique para começar',
    imgStart: false,
    img: require('../images/tran-1.svg').default,
    alt: 'Transações ilimitadas',
    dark: true,
    primary: true,
    darkText: false,
};

export const HomeObjTwo = {
    id: 'saiba',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Acesso ilimitado',
    headline: 'Entre na sua conta a qualquer momento', 
    description: 'Estamos sempre ao seu alcance, onde quer que você esteja. Com uma conexão à internet e um dispositivo, você tem tudo o que precisa',
    buttonLabel: 'Veja mais',
    imgStart: true,
    img: require('../images/acess-1.svg').default,
    alt: 'Acesso ilimitado',
    dark: false,
    primary: false,
    darkText: true,
};

export const HomeObjThree = {
    id: 'cadastro',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Junte-se a nós',
    headline: 'Crie sua conta, é fácil e rápido.', 
    description: 'Tenha tudo configurado e pronto em menos de 10 minutos. Basta adicionar suas informações e pronto!',
    buttonLabel: 'Começe agora',
    imgStart: false,
    img: require('../images/cont-1.svg').default,
    alt: 'Cadastro',
    dark: false,
    primary: false,
    darkText: true,
};
